---
chainsmith_nodes: "{% set nodes = [] %}{% for node in (groups.pgnodes + groups.minio) %}{% do nodes.append(hostvars[node].ansible_facts.fqdn) %}{% endfor %}{{ nodes }}"
chainsmith_ips: "{% set nodes = [] %}{% for node in (groups.pgnodes + groups.minio) %}{% do nodes.append(hostvars[node].ansible_host) %}{% endfor %}{{ nodes }}"
chainsmith_servers: "{% set nodes = {} %}{% for node in (groups.pgnodes + groups.minio) %}{% do nodes.update({hostvars[node].ansible_facts.fqdn: chainsmith_nodes+chainsmith_ips}) %}{% endfor %}{{ nodes }}"
chainsmith_server_cert_path: '{{ server_cert_path }}'
chainsmith_node_group: pgnodes
chainsmith_users:
  pgnodes:
    - postgres
    - avchecker
    - pgquartz
    - pgfga
  haproxy:
    - pgroute66
  minio:
    - minio
