---
etcd_secure: False
etcd_data_dir: /var/lib/etcd
etcd_install_dir: /usr/bin
etcd_iface_cluster: eth1
etcd_additional_envvars:
  ETCD_AUTO_COMPACTION_RETENTION: 1
  ETCD_AUTO_COMPACTION_MODE: revision
