---

haproxy_timeout_client: 10800s
haproxy_checkport: "9201"

haproxy_config:
  ReadWrite:
    backend_port: "{{ stolon_clusters.cluster1.sysconfig.stkeeper.pg_port }}"
    frontend_port: 35433
  Proxy:
    backend_port: "{{ stolon_clusters.cluster1.sysconfig.stproxy.port }}"
    frontend_port: 35434
  ReadOnly:
    backend_port: "{{ stolon_clusters.cluster1.sysconfig.stkeeper.pg_port }}"
    frontend_port: 35435

haproxy_frontends:
   # name is used to define the cluster (script strips all after first dash)
 - name: "cluster1-ReadWrite-frontend"
   address: "*"
   port: "{{ haproxy_config.ReadWrite.frontend_port }}"
   mode: "{{ haproxy_default_mode }}"
   backend: "cluster1-ReadWrite-backend"
   timeout_client: "{{ haproxy_timeout_client }}"
   # name is used to define the cluster (script strips all after first dash)
 - name: "cluster1-ReadOnly-frontend"
   address: "*"
   port: "{{ haproxy_config.ReadOnly.frontend_port }}"
   mode: "{{ haproxy_default_mode }}"
   backend: "cluster1-ReadOnly-backend"
   timeout_client: "{{ haproxy_timeout_client }}"
   # name is used to define the cluster (script strips all after first dash)
 - name: "cluster1-Proxy-frontend"
   address: "*"
   port: "{{ haproxy_config.Proxy.frontend_port }}"
   mode: "{{ haproxy_default_mode }}"
   backend: "cluster1-Proxy-backend"
   timeout_client: "{{ haproxy_timeout_client }}"

haproxy_backends:
 - name: "cluster1-ReadWrite-backend"
   mode: "{{ haproxy_default_mode }}"
   balance_method: "leastconn"
   options:
     - "external-check"
   params:
     - "external-check command  /opt/pgroute66/checkpgprimary.sh"
   timeout_server: "{{ haproxy_timeout_client }}"
   servers:
     - name: "db-1.local"
       address: "172.30.1.31"
       port: "{{ haproxy_config.ReadWrite.backend_port }}"
       checkport: "{{ haproxy_checkport }}"
     - name: "db-2.local"
       address: "172.30.1.32"
       port: "{{ haproxy_config.ReadWrite.backend_port }}"
       checkport: "{{ haproxy_checkport }}"
     - name: "db-3.local"
       address: "172.30.1.33"
       port: "{{ haproxy_config.ReadWrite.backend_port }}"
       checkport: "{{ haproxy_checkport }}"
 - name: "cluster1-ReadOnly-backend"
   mode: "{{ haproxy_default_mode }}"
   balance_method: "leastconn"
   options:
     - "external-check"
   params:
     - "external-check command  /opt/pgroute66/checkpgstandby.sh"
   timeout_server: "{{ haproxy_timeout_client }}"
   servers:
     - name: "db-1.local"
       address: "172.30.1.31"
       port: "{{ haproxy_config.ReadOnly.backend_port }}"
       checkport: "{{ haproxy_checkport }}"
     - name: "db-2.local"
       address: "172.30.1.32"
       port: "{{ haproxy_config.ReadOnly.backend_port }}"
       checkport: "{{ haproxy_checkport }}"
     - name: "db-3.local"
       address: "172.30.1.33"
       port: "{{ haproxy_config.ReadOnly.backend_port }}"
       checkport: "{{ haproxy_checkport }}"
 - name: "cluster1-Proxy-backend"
   mode: "{{ haproxy_default_mode }}"
   balance_method: "leastconn"
   options:
     - "external-check"
   params:
     - "external-check command  /opt/pgroute66/checkpgprimary.sh"
   timeout_server: "{{ haproxy_timeout_client }}"
   servers:
     - name: "db-1.local"
       address: "172.30.1.31"
       port: "{{ haproxy_config.Proxy.backend_port }}"
       checkport: "{{ haproxy_checkport }}"
     - name: "db-2.local"
       address: "172.30.1.32"
       port: "{{ haproxy_config.Proxy.backend_port }}"
       checkport: "{{ haproxy_checkport }}"
     - name: "db-3.local"
       address: "172.30.1.33"
       port: "{{ haproxy_config.Proxy.backend_port }}"
       checkport: "{{ haproxy_checkport }}"
# - name: "cluster1-Bouncer-backend"
