---
postgresql_bindir: "/usr/pgsql-{{ stolon_pg_version }}/bin/"
postgresql_log_directory: /var/log/postgresql

# /tmp is hardcoded by stolon. :(
postgresql_socketdir: "/tmp"

postgresql_timeout_parameters:
  # Sluit de idle connectie na 60 minuten
  idle_in_transaction_session_timeout: "60min"
  statement_timeout: "60min"

postgresql_log_parameters:
  # Logging
  log_destination: "csvlog"
  logging_collector: "on"
  # syslog_facility: "LOCAL1"
  # syslog_ident: "pg{{ postgresql_version }}"
  log_directory: "{{ postgresql_log_directory }}"
  log_file_mode: "0600"
  log_filename: "postgresql-%Y%m%d.log"
  log_rotation_size: "1GB"
  log_line_prefix: "%m [%p]: [%l-1] db=%d,user=%u,app=%a,client=%h "
  log_error_verbosity: "verbose"
  log_statement: "ddl"
  log_min_error_statement: "error"
  log_min_messages: "warning"
  log_min_duration_statement: "5000"
  log_connections: "on"
  log_disconnections: "on"
  log_truncate_on_rotation: "on"
