---
walg_bucket_name: "{{ bucket_name }}"
walg_bucket_ca_file: ~/.wal-g/certs/bucket_ca.crt

walg_pg_datadir: "{{stolon_data_dir }}/postgres"
walg_pg_bindir: "{{ postgresql_bindir }}"
walg_pg_hostname: "{{ postgresql_socketdir }}"
walg_backup_skip_window: 8
# Keep  days of backups
walg_cron_mailto: "{{ cron_mailto }}"

walg_postgresql_parameters:
  archive_command: "/opt/wal-g/scripts/archive.sh %p"
  #can be used when we have configured buckets working with wal-g
  #restore_command: "/opt/wal-g/scripts/archive_restore.sh %f %p"
  archive_mode: "on"
  listen_addresses: "'*'"
  log_filename: "postgresql.log"
  log_line_prefix: " "
  max_wal_senders: "3"
  wal_level: archive

walg_bucket_cert: "{{ certs.server.chain }}"

walg_bucket_defaults:
  WALG_S3_PREFIX: "s3://{{ walg_bucket_name }}/{{ cluster_name }}"
  AWS_ACCESS_KEY_ID: "{{ minio_access_key }}"
  AWS_SECRET_ACCESS_KEY: "{{ minio_secret_key }}"
  AWS_ENDPOINT: "https://{{ hostvars[groups['backup'][0]].ansible_fqdn }}"
  AWS_S3_FORCE_PATH_STYLE: true
  S3_CA_CERT_FILE: /var/lib/pgsql/.postgresql/root.crt

walg_cert_folders: {}
walg_cert_files: {}
