---
walg_bucket_name: "{{ bucket_name }}"
walg_bucket_ca_file: ~/.wal-g/certs/bucket_ca.crt

walg_pg_datadir: "{{stolon_data_dir }}/postgres"
walg_pg_bindir: "{{ postgresql_bindir }}"
walg_pg_hostname: "{{ postgresql_socketdir }}"
walg_backup_skip_window: 8
# Keep  days of backups
walg_cron_mailto: "{{ cron_mailto }}"

walg_postgresql_parameters:
  archive_command: "/opt/wal-g/scripts/archive.sh %p"
  #can be used when we have configured buckets working with wal-g
  #restore_command: "/opt/wal-g/scripts/archive_restore.sh %f %p"
  archive_mode: "on"
  listen_addresses: "'*'"
  log_filename: "postgresql.log"
  log_line_prefix: " "
  max_wal_senders: "3"
  wal_level: archive

walg_bucket_cert: "{{ certs.server.chain }}"

walg_bucket_defaults:
  WALG_S3_PREFIX: "s3://{{ walg_bucket_name }}/{{ cluster_name }}"
  AWS_ACCESS_KEY_ID: "{{ minio_access_key }}"
  AWS_SECRET_ACCESS_KEY: "{{ minio_secret_key }}"
  AWS_ENDPOINT: "https://{{ hostvars[groups['backup'][0]].ansible_fqdn }}"
  AWS_S3_FORCE_PATH_STYLE: true
  S3_CA_CERT_FILE: "{{ getent_passwd[walg_user][4] }}/.postgresql/root.crt"

walg_cert_folders: {}
walg_cert_files: {}

walg_clusters:
  cluster1:
    pg_datadir: "{{ postgresql_data_mountpoint }}/cluster1/postgres"
    pg_port: 5432
    s3_prefix: "s3://cluster1"
    logfolder: "{{ walg_logfolder }}/cluster1/"
    cron:
      enabled: "{{ walg_cron_enabled }}"
      minute: "{{ walg_cron_minute }}"
      hour: "{{ walg_cron_hour }}"
  cluster2:
    pg_datadir: "{{ postgresql_data_mountpoint }}/cluster2/postgres"
    pg_port: 5433
    s3_prefix: "s3://cluster2"
    logfolder: "{{ walg_logfolder }}/cluster2/"
    cron:
      enabled: "{{ walg_cron_enabled }}"
      minute: "{{ walg_cron_minute }}"
      hour: "{{ walg_cron_hour }}"
